#[cfg(feature = "server")]
pub mod document;
#[cfg(feature = "server")]
pub mod document_actor;
#[cfg(feature = "server")]
pub mod ot;
#[cfg(feature = "server")]
pub mod snapshot;
#[cfg(feature = "server")]
pub mod awareness;
#[cfg(feature = "server")]
pub mod etcd;
#[cfg(feature = "server")]
pub mod op_queue;
pub mod storage;

#[cfg(feature = "server")]
pub use document::DocumentService;
#[cfg(feature = "server")]
pub use document_actor::DocumentActorManager;
#[cfg(feature = "server")]
pub use ot::OTService;
#[cfg(feature = "server")]
pub use snapshot::SnapshotService;
#[cfg(feature = "server")]
pub use awareness::AwarenessService;
#[cfg(feature = "server")]
pub use etcd::EtcdService;
#[cfg(feature = "server")]
pub use op_queue::OpQueueService;
pub use storage::StorageService;
